# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9959cba9f9c02d37d30e8030a7d39f58214f4083b78e3d02f283a3207c4ab889387589969d09d7adcb566a610752fc58288975dab99cb99417ad32648379a0b

test:
  secret_key_base: 5b7f018b642e974e31808e2c9da37335f710a159f3f4c8ee44b156861b1ea89387ca194b40d56cf7eaacd10ec3176e588c1ad6be691c99bf8e376cd72c0e62f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
